project:
  type: website
  output-dir: docs

website:
  title: "Coby Darer"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: Resume2.pdf
        text: Resume
      - about.qmd
      - project.qmd
    
    tools:
      - icon: linkedin
        href: https://www.linkedin.com/in/jacob-coby-darer-48318a378/
      - icon: github
        href: https://github.com/cobydarer
format:
  html:
    theme: zephyr  # flatly, litera, lumen, lux, minty, pulse, sandstone, zephyr, quartz, yeti, cosmo, sketchy
    css: styles.css
    toc: true

execute: 
  freeze: auto

